### ISSUE TITLE
"CMSIS-DAP" in USB product string

### ISSUE THREAD

**Issue by adamgreig** [orbcode/orbtrace#7]
Would you consider adding a "CMSIS-DAP" string to the orbtrace USB product string? It's not required by the CMSIS-DAP spec since you do have it in the interface string, but it would make a couple of things easier:

* Some software currently just checks the product string (such as https://github.com/probe-rs/probe-rs), since reading interface strings generally requires permission on Linux, and can't be done through hidapi for CMSIS-DAPv1 HID access
* If people have openocd installed (which I guess many users will), on Linux it adds a udev rule granting user access to all devices with CMSIS-DAP in the interface string, so users wouldn't need to add custom udev rules for orbtrace: `ATTRS{product}=="*CMSIS-DAP*", MODE="660", GROUP="plugdev", TAG+="uaccess"` in `/lib/udev/rules.d/60-openocd.rules`.

As far as I can tell (i.e. I've also implemented a CMSIS-DAP probe as a composite USB device performing other non-CMSIS-DAP functionality) it doesn't harm anything to have "CMSIS-DAP" in the product string; for example I used "FFP r1 with CMSIS-DAP Support" for the product string).

Either way I plan to modify probe-rs to detect devices that only have the string in the interface, but it would never be able to detect the HID interface that way, or work without udev rules being set up.

**Comment by zyp** [comment]
The way I see it, there's no real downsides of adding it, except that one could argue out of principle that «it doesn't belong there, Orbtrace is a modular solution that may or may not have a CMSIS-DAP interface», but that wouldn't be harder than only appending it when a CMSIS-DAP v1 interface is present.

In more practical terms, it's a question of whether we want to improve CMSIS-DAP v1 compatibility or be a driving force for v2 adoption. I'm inclined to argue for the latter, since that'll help us get to a point in the future where v2 support is good enough that we can drop the v1 interface from the default build and thereby save resources.

The udev argument is somewhat compelling, but we still need to ship our own udev rules, both because we can't rely on openocd being installed, because that rule doesn't cover the bootloader and because in the future we'll have builds that instead of CMSIS-DAP e.g. runs a gdbserver directly on the Orbtrace itself.

In any case, I don't want to make an unilateral decision on this, so I'm leaving the issue open for discussion.

**Comment by mubes** [comment]
Adam,

Thanks for this, and especially all your work on probe-rs! zyp and I kicked this around earlier. I think we're both of the weak-opinion that we should leave arrangements as they are. Some of the argument goes that Orbtrace isn't primarily a debug interface...its just one of its features and, indeed, Debug might not be present in some instantiations. TBH I can't imagine what those would be, but they're certainly technically possible because everything is quite modular.

As a slight aside, you can identify what capabilities a particular build does have by looking at the interface strings;

```
$ lsusb -d 1209:3443 -v | grep iInterface
      iInterface              4 Trace (TPIU)
      iInterface              5 CMSIS-DAP v1
      iInterface              6 CMSIS-DAP v2
      iInterface              7 Target power
      iInterface              8 Version: ad05875-dirty
```

Also, if we have a fallback functionality of CMSIS-DAPv1 when permissions are mis-configured then folks may well not realise the full capability of the device...they'll just assume it's slow.  Quite a lot of adaptor code doesn't tell you what interface (v1 or v2) it's actually using so it's reasonably difficult to chase that one to ground, so from that perspective I think I'd prefer to not have it work at all than have a false perception of the device :-)  Finally, I can easily imagine scenarios where v1 functionality goes completely (e.g. when we're short of endpoints) and then we'd have to change the product name or something.

These are, however, only weak arguments, and we're both aware there may be other points of view. We'll leave this open for a while and see if anyone comes with a counter argument that should be considered...perhaps there's something out there that *must* have the name in the device string that we simply haven't considered.

DAVE

**Comment by mubes** [comment]
Folks, we've had this open all summer and no other opinions have come to light. Given that it's not been a burning field issue and most software seems to be working very well with ORBTrace now, I propose that we should close this. If you don't agree or want to extend the discussions please reply and we'll re-open.  DAVE
